name: Pipeline CI

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_REPOSITORY: ghcr.io/${{ github.repository_owner }}/comments:{{ github.run_attempt }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker Image
      run: docker build -t $IMAGE_REPOSITORY .

    - name: Push Docker Image
      run: docker push IMAGE_REPOSITORY