name: Pipeline CI/CD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_REPOSITORY: ghcr.io/${{ github.repository }}/comments:${{ github.run_attempt }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build Docker Image
      run: docker build -f Dockerfile -t $IMAGE_REPOSITORY .
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker Image
      run: docker push $IMAGE_REPOSITORY

    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  

    - name: Update kubeconfig for Amazon EKS
      run: aws eks update-kubeconfig --region us-east-1 --name eks-cluster

    - name: Update Kubernetes Manifests
      run: |
        sed -i "s|image: .*|image: $IMAGE_REPOSITORY|g" k8s/*.yaml

    - name: Apply Kubernetes Manifests
      run: kubectl apply -f k8s/