name: Pipeline CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_REPOSITORY: ghcr.io/${{ github.repository }}/comments:${{ github.run_attempt }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build Docker Image
      run: docker build -f Dockerfile -t $IMAGE_REPOSITORY .
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker Image
      run: docker push $IMAGE_REPOSITORY